- name: Install updates and restart
  block:
    - name: Update Server packages
      dnf:
        update_cache: yes
        name: "*"
        state: latest
      register: dnfcommandout

    - name: Print errors if dnf failed
      debug:
        msg: "dnf command produced errors"
      when: dnfcommandout is not defined

    - name: Check to see if we need a reboot
      command: needs-restarting -r
      register: result
      ignore_errors: yes

    - name: Reboot the server if needed
      reboot:
      when: result.rc == 1

  when: 
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == '8'

- name: Install updates and restart
  block:
    - name: Update package cache
      package:
        update_cache: yes

    - name: Update local system
      package:
        upgrade: yes
      register: pkgcommandout

    - name: Print errors if pkg inst failed
      debug:
        msg: "Package produced errors"
      when: pkgcommandout is not defined

    - name: Check to see if we need to bounce!
      command: needs-restarting -r
      register: result
      ignore_errors: true

    - name: Reboot if needed (command host, Ill die here!)
      command: shutdown -r now "Ansible updates triggered"
      
  when: ansible_facts['distribution'] == "Archlinux"
